base_llm:
  type_llm: "bedrock" # "bedrock" or "openai"
  temperature: 0.0

secret_manager:
  secret_name: "test-hubsync"
  region_name: "us-east-1"

openai_llm:
  model_name: "gpt-3.5-turbo-16k"

bedrock_llm:
  model_name: "ai21.j2-ultra-v1"
  embedding_model_name: "amazon.titan-embed-text-v1"
  region_name: "us-east-1"
  topP: 1
  maxTokens: 8191

splitter:
  chunk_size: 1500
  chunk_overlap: 200

retriever:
  aws_service: "aoss"
  aws_region: "us-east-1"
  opensearch_index_name: "hubsync-ai-assistant"

conversational_chain:
  chain_type_retriever: "stuff"
